#!/usr/bin/env python3
"""Create the first editable files for a generic RNA-seq project."""

from __future__ import annotations

import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    value = input(f"{prompt}{suffix}: ").strip()
    return value or default


def split_projects(raw: str) -> list[str]:
    projects = [item.strip() for item in raw.replace(",", " ").split()]
    return [project for project in projects if project]


def shell_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_file(path: Path, content: str, force: bool, dry_run: bool) -> bool:
    if path.exists() and not force:
        print(f"[SKIP] Exists: {path}")
        return False
    if dry_run:
        action = "Would overwrite" if path.exists() else "Would write"
        print(f"[DRY-RUN] {action}: {path}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"[OK] Wrote: {path}")
    return True


def user_settings_content(args: argparse.Namespace, projects: list[str]) -> str:
    refs: list[str] = []
    if args.genome_url:
        refs.append(f"export GENOME_URL={shell_quote(args.genome_url)}")
    if args.transcripts_url:
        refs.append(f"export TRANSCRIPTS_URL={shell_quote(args.transcripts_url)}")
    if args.gff3_url:
        refs.append(f"export GFF3_URL={shell_quote(args.gff3_url)}")
    if args.gtf_url:
        refs.append(f"export GTF_URL={shell_quote(args.gtf_url)}")
    if args.ref_genome_fa:
        refs.append(f"export REF_GENOME_FA={shell_quote(args.ref_genome_fa)}")
    if args.ref_transcripts_fa:
        refs.append(f"export REF_TRANSCRIPTS_FA={shell_quote(args.ref_transcripts_fa)}")
    if args.ref_gff3:
        refs.append(f"export REF_GFF3={shell_quote(args.ref_gff3)}")
    if args.ref_gtf:
        refs.append(f"export REF_GTF={shell_quote(args.ref_gtf)}")
    if not refs:
        refs.append("# export TRANSCRIPTS_URL=\"https://example.org/transcripts.fa.gz\"")
        refs.append("# export GTF_URL=\"https://example.org/annotation.gtf.gz\"")

    if args.quant_method == "star":
        run_salmon_index = "0"
        run_star_gtf_index = "1"
    else:
        run_salmon_index = "1"
        run_star_gtf_index = "0"

    return f"""#!/usr/bin/env bash

# Generated by scripts/bootstrap_project.py.
# Edit paths and biological defaults here; leave config/pipeline_config.sh alone.

export PIPELINE_NAME={shell_quote(args.pipeline_name)}
export ORGANISM_NAME={shell_quote(args.organism)}
export PIPELINE_PROJECTS={shell_quote(" ".join(projects))}

export SCRATCH_ROOT={shell_quote(args.scratch_root)}
export CONDA_BASE={shell_quote(args.conda_base)}

{chr(10).join(refs)}

export QUANT_METHOD={shell_quote(args.quant_method)}
export FASTQ_LAYOUT={shell_quote(args.layout)}
export PIPELINE_EXECUTOR={shell_quote(args.executor)}
export LOCAL_CPUS_PER_TASK={args.local_cpus}
export PIPELINE_STORAGE_MODE={shell_quote(args.storage_mode)}
export PIPELINE_COMPRESS_RESULTS=1

export RUN_SALMON_INDEX={run_salmon_index}
export RUN_STAR_GTF_INDEX={run_star_gtf_index}
export RUN_STAR_INDEX=0
export STAR_WRITE_BAM=0
export STAR_LIMIT_BAM_SORT_RAM=24000000000

export RUN_BATCH_CORRECTION=0
export RUN_DTU_ANALYSIS=0
export RUN_SPLICING_ANALYSIS=0
export RUN_WGCNA_ANALYSIS=0
export RUN_MFUZZ_ANALYSIS=0
export RUN_GENE_REPORT=0

# Adjust these to match your metadata columns before enabling downstream modules.
export DEG_TEST_VARIABLES="condition,stage,tissue,sex,batch"
export WGCNA_TRAIT_COLUMNS="condition,stage,tissue,sex,batch,dataset"
export MFUZZ_TIME_VARIABLE="stage"
export MFUZZ_TIME_LEVELS=""

export RNA_TOOLS_ENV="rna-tools"
export PYTHON_ENV="python-list"
export R_ANALYSIS_ENV="r-analysis"
export BATCH_CORRECTION_ENV="batch-correction"
export DTU_ANALYSIS_ENV="r-analysis"
export SPLICING_ENV="splicing"
export WGCNA_ENV="r-analysis"
export MFUZZ_ENV="r-analysis"
"""


def download_config_content(project: str, args: argparse.Namespace) -> str:
    link_file = f"ena-file-download-read_run-{project}-fastq_ftp.sh"
    return f"""project:
  id: {project}
  organism: configured_in_config_user_settings
  source: ENA
  accession: {project}

download:
  link_file: {link_file}
  protocol: ftp
  threads: {args.download_threads}
  retry: true
  continue_download: true

library:
  layout: {args.layout}
  compression: gz
  read_suffix:
    r1: "_1.fastq.gz"
    r2: "_2.fastq.gz"

validation:
  check_md5: false
  expected_files: auto

metadata:
  metadata_file:
  parser:
"""


def link_file_content(project: str) -> str:
    return f"""# Add ENA/SRA FASTQ URLs for {project}, one per line.
# This file may also contain the ENA-generated wget script; the pipeline
# extracts ftp:// and https:// links automatically.
#
# Example:
# ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR000/ERR000001/ERR000001_1.fastq.gz
# ftp://ftp.sra.ebi.ac.uk/vol1/fastq/ERR000/ERR000001/ERR000001_2.fastq.gz
"""


def parser_yaml_content(project: str, args: argparse.Namespace) -> str:
    sample_source = args.sample_source
    return f"""dataset: {project}

defaults:
  dataset: {project}
  condition: unknown
  stage: unknown
  tissue: unknown
  sex: unknown
  batch: B0
  replicate:
  lane:

columns:
  sample_field: {sample_source}
  run_field: run_accession

preserve_columns:
  {sample_source}: raw_sample_id
  study_accession: study_accession
  scientific_name: scientific_name
  library_name: library_name

# Edit regex_map entries to match this project's sample names.
# Keep values organism-neutral: control, treated, leaf, root, time_1h, etc.
parsing:
  condition:
    source: {sample_source}
    regex_map:
      "control|ctrl|mock": control
      "treated|treatment|case": treated

  stage:
    source: {sample_source}
    regex_map:
      "stage1|time1|t1": stage1
      "stage2|time2|t2": stage2

  tissue:
    source: {sample_source}
    regex_map:
      "whole": whole_body

  sex:
    source: {sample_source}
    regex_map:
      "female|^F[_-]": female
      "male|^M[_-]": male

  replicate:
    source: {sample_source}
    regex_extract: "(?:rep|replicate|R)[_-]?(\\d+)"

sample_id_components:
  - field: dataset
    width: 10
  - field: condition
    width: 8
  - field: stage
    width: 8
  - field: tissue
    width: 8
  - field: sex
    width: 3
  - field: replicate
    replicate: true
  - field: batch

final_columns:
  - sample_id
  - file_prefix
  - raw_sample_id
  - condition
  - stage
  - tissue
  - sex
  - batch
  - replicate
  - dataset
  - lane
  - run_accession
  - study_accession
  - scientific_name
  - library_name
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Create config/user_settings.sh and per-project starter files."
    )
    parser.add_argument("--project", action="append", help="Project accession. Can be repeated or comma/space-separated.")
    parser.add_argument("--organism")
    parser.add_argument("--pipeline-name", default="rnaseq_project")
    parser.add_argument("--scratch-root")
    parser.add_argument("--conda-base")
    parser.add_argument("--quant-method", choices=["salmon", "star"], default="salmon")
    parser.add_argument("--layout", choices=["paired", "single"], default="paired")
    parser.add_argument("--executor", choices=["slurm", "local"], default="slurm")
    parser.add_argument("--local-cpus", type=int, default=8)
    parser.add_argument("--storage-mode", choices=["full", "balanced", "minimal"], default="full")
    parser.add_argument("--download-threads", type=int, default=8)
    parser.add_argument("--sample-source", default="sample_id")
    parser.add_argument("--genome-url", default="")
    parser.add_argument("--transcripts-url", default="")
    parser.add_argument("--gff3-url", default="")
    parser.add_argument("--gtf-url", default="")
    parser.add_argument("--ref-genome-fa", default="")
    parser.add_argument("--ref-transcripts-fa", default="")
    parser.add_argument("--ref-gff3", default="")
    parser.add_argument("--ref-gtf", default="")
    parser.add_argument("--force", action="store_true", help="Overwrite existing generated files.")
    parser.add_argument("--dry-run", action="store_true", help="Print files that would be created without writing them.")
    parser.add_argument("--non-interactive", action="store_true", help="Fail instead of asking for missing required values.")
    args = parser.parse_args()

    raw_projects = " ".join(args.project or [])
    if not raw_projects and not args.non_interactive:
        raw_projects = ask("ENA/SRA project accession(s), separated by space")
    projects = split_projects(raw_projects)
    if not projects:
        raise SystemExit("[ERROR] Provide at least one --project.")
    args.projects = projects

    for attr, prompt, default in [
        ("organism", "Organism name", ""),
        ("scratch_root", "Scratch/work directory on the server", "/scratch/$USER/rnaseq_project"),
        ("conda_base", "Conda base directory", "/path/to/miniconda3"),
    ]:
        if not getattr(args, attr) and not args.non_interactive:
            setattr(args, attr, ask(prompt, default))
        if not getattr(args, attr):
            raise SystemExit(f"[ERROR] Missing required option --{attr.replace('_', '-')}.")

    return args


def main() -> None:
    args = parse_args()
    projects = args.projects

    write_file(
        REPO_ROOT / "config" / "user_settings.sh",
        user_settings_content(args, projects),
        args.force,
        args.dry_run,
    )

    for project in projects:
        dataset_dir = REPO_ROOT / "020-data-download" / "datasets" / project
        write_file(dataset_dir / "config.yaml", download_config_content(project, args), args.force, args.dry_run)
        write_file(
            dataset_dir / f"ena-file-download-read_run-{project}-fastq_ftp.sh",
            link_file_content(project),
            args.force,
            args.dry_run,
        )
        write_file(
            REPO_ROOT
            / "025-parse"
            / "020-metadata_parsers"
            / project
            / "configs"
            / f"{project}.yaml",
            parser_yaml_content(project, args),
            args.force,
            args.dry_run,
        )

    print("\nNext steps:")
    print("  1. Edit config/user_settings.sh reference paths/URLs.")
    print("  2. Add FASTQ URLs to each 020-data-download/datasets/<PROJECT>/ena-file-download... file.")
    print("  3. Edit each metadata parser YAML regex_map to match sample names.")
    print("  4. Run: bash scripts/validate_config.sh config/pipeline_config.sh")
    print("  5. Preview: bash rnaseq_pipeline.sh --all --dry-run")


if __name__ == "__main__":
    main()
